### ISSUE TITLE
Installer detects Delphi XE7 as XE8

### ISSUE THREAD

**Issue by IL2** [rfrezino/RFindUnit#14]
Wrong detection of Delphi XE7 as XE8 version and may be some others.
This particular registry path \Software\Embarcadero\BDS\13.0 is not used and there is no such version as XE9, because 10 Seattle is right after XE8.
So XE paths in uDelphiInstallationCheck.pas should be like that
XE    '\Software\Embarcadero\BDS\8.0',
XE2    '\Software\Embarcadero\BDS\9.0',
XE3    '\Software\Embarcadero\BDS\10.0',
XE4    '\Software\Embarcadero\BDS\11.0',
XE5    '\Software\Embarcadero\BDS\12.0',
XE6    '\Software\Embarcadero\BDS\14.0'
XE7    '\Software\Embarcadero\BDS\15.0',
XE8    '\Software\Embarcadero\BDS\16.0',
10 Seattle    '\Software\Embarcadero\BDS\17.0'

**Comment by rfrezino** [comment]
Thank you, fixed.

**Comment by IL2** [comment]
Sorry, Installer.exe is still not fixed and I can't just build it because of #16.
