### ISSUE TITLE
FixInsight warning: Equal then/else statement

### ISSUE THREAD

**Issue by IL2** [rfrezino/RFindUnit#15]
I've run FixInsight on your installer project, and this warning has surfaced:
[FixInsight Warning] FindUnit.Utils.pas(103): W507 THEN statement is equal to ELSE statement

function Fetch(var AInput: string; const ADelim: string = ''; const ADelete: Boolean = True;
  const ACaseSensitive: Boolean = False): string; inline;
var
  LPos: Integer;
begin
  if ACaseSensitive then
  begin
    if ADelim = #0 then
    begin
      // AnsiPos does not work with #0
      LPos := Pos(ADelim, AInput);
    end
    else
    begin
      LPos := Pos(ADelim, AInput);
    end;

**Comment by rfrezino** [comment]
Yeap, I saw it too. This function is from Indy library, I didn't change the original code.

**Comment by IL2** [comment]
I've glanced upon Pos and AnsiPos in System.pas
It seems that the comment is correct - AnsiPos will have problems in Unicode when searching for substring of #0 due to StrPosLen function

function AnsiPos(const Substr, S: string): Integer;
var
  P: PChar;
begin
  Result := 0;
{$IFDEF UNICODE}
  P := StrPosLen(PChar(S), PChar(SubStr), Length(S), Length(SubStr));
{$ELSE}
  P := AnsiStrPos(PChar(S), PChar(SubStr));
{$ENDIF}
  if P <> nil then
    Result := (IntPtr(P) - IntPtr(PChar(S))) div SizeOf(Char) + 1;
end;

function StrPosLen(const Str1, Str2: PWideChar; Len1, Len2: Integer): PWideChar;
var
  I: Integer;
begin
  Result := nil;
  if Len1 = 0 then
    Exit;
  if Len2 = 0 then
    Exit;
  for I := 0 to Len1 - Len2 do
  begin
    if (Str1[I] <> #0) and (StrLComp(PWideChar(PByte(Str1) + I * SizeOf(WideChar)), Str2, Len2) = 0) then
    begin
      Result := PWideChar(PByte(Str1) + I * SizeOf(WideChar));
      Exit;
    end;
  end;
end;

As I can see, this doesn't relate to Pos function and that condition "if ADelim = #0 then" can be discarded safely.

**Comment by rfrezino** [comment]
Thank you. So I'll remove it.
