### ISSUE TITLE
Can't build installer - Unit 'cxGraphics' not found

### ISSUE THREAD

**Issue by IL2** [rfrezino/RFindUnit#16]
Sorry, I can't build installer project due cx* and dx* units are missing:
[dcc32 Fatal Error] uMain.pas(7): F2613 Unit 'cxGraphics' not found.

**Comment by rfrezino** [comment]
These units are not necessary, you can just remove then from there. I'll remove it and commit in some minutes.

**Comment by rfrezino** [comment]
I sent the new source can you check ?

**Comment by IL2** [comment]
Yep, after pulling changes, adding DelphiAST and Log4pascal library paths, Installer.exe has been built.
Thank you.
