### ISSUE TITLE
Undeclared identifier: 'TValueData'

### ISSUE THREAD

**Issue by IL2** [rfrezino/RFindUnit#17]
Sorry, compiling RFindUnit.dpk in Seattle throws this:
[dcc32 Error] SuperObject.pas(141): E2003 Undeclared identifier: 'TValueData'
Probably because of
{$if defined(VER210) or defined(VER220)}
  {$define HAVE_RTTI}
{$ifend}
{$IFDEF HAVE_RTTI}
  ,Generics.Collections, RTTI, TypInfo
{$ENDIF}
HAVE_RTTI define doesn't fire.

After changing to
{$if defined(VER210) or defined(VER220) or defined(VER300)}
  {$define HAVE_RTTI}
{$ifend}
compilation stops at
[dcc32 Error] SuperObject.pas(1062): E2003 Undeclared identifier: 'DecimalSeparator'
[dcc32 Error] SuperObject.pas(1080): E2003 Undeclared identifier: 'DecimalSeparator'

After changing to DecimalSeparator to FormatSettings.DecimalSeparator it finally compiles.

**Comment by IL2** [comment]
I 've changed to
{$if CompilerVersion >= 14.0}
 {$define HAVE_RTTI}
 {$ifend}
which is enough for XE and Seattle, but not for XE2 and XE7.

**Comment by rfrezino** [comment]
Can you send a pull request for it ?
I don't have Delphi Seatle :/

**Comment by IL2** [comment]
Sending a pull request is very new to me. Is it needed to fork a project to make a pull request?

**Comment by rfrezino** [comment]
Yes. Do you use git  ? 
You fork this to your github, than you create a branch, do the modifications that you need. Send it to to your account, and create a pull request. It seems to be a lot of steps, but it's really easy. 

I'm thinking about use, jedi.inc as standard ifdefs. Take a look https://jpst.it/Fi-m
We can use this inc, and use the defines there.
For example, to know if the Delphi Supports RTTI we can just use {$IFDEF HAS_UNIT_RTTI}

**Comment by rfrezino** [comment]
Another thing, I don't think to give support to old delphi versions (those that don't have gennerics and RTTI). So, for this situation, I can remove the verification and "presume" that everybody have rtti.

**Comment by IL2** [comment]
Yep. too many steps, may be later if needed.
I agree with your assumption on supporting at least XE+.
Anyway current https://github.com/project-jedi/jcl/blob/master/jcl/source/include/jcl.inc is a good point to reference to for Delphi features and versions.

**Comment by rfrezino** [comment]
I'll ad jcl.inc later and use it.
