### ISSUE TITLE
Search in project units not working

### ISSUE THREAD

**Issue by edwinyzh** [rfrezino/RFindUnit#22]
No result when searching for an identifier defined in a .pas in the project. Attached screenshot below.

![2016-02-18_14h26_47](https://cloud.githubusercontent.com/assets/541197/13135551/9796f6ee-d64c-11e5-8851-6f3af723a17a.png)

**Comment by rfrezino** [comment]
Strange, I can repeat the same problem here. 
Some special condition ? Some error on log ?

**Comment by edwinyzh** [comment]
I'll get back to you next week.

**Comment by rfrezino** [comment]
Try the master branch

**Comment by edwinyzh** [comment]
@rfrezino Sorry, but I'm extremely busy and I'll try to get back to you soon.

**Comment by edwinyzh** [comment]
@rfrezino  I decided to give a try at the end, there is no more "loading...' message - it shows "Ready" now. But I still couldn't find a class defined in my project... I'm not sure I'm doing anything wrong...

**Comment by rfrezino** [comment]
Fixed!
