### ISSUE TITLE
Installer failed :(

### ISSUE THREAD

**Issue by jaclas** [rfrezino/RFindUnit#23]
See screen:

https://snap.ashampoo.com/uploads/2016-02-18/r5jrBSVx.png

**Comment by rfrezino** [comment]
Jaclas, good morning.
Peter had the same problem, he sent me and e-mail and told that was a problem with superobject. (it seems to be a simple thing).
I don't have access to Delphi 10, if you can take a look on it and send a pull request with the solution it should be very good.
