### ISSUE TITLE
Update OmniThreadLibrary to fix GUIDCompare

### ISSUE THREAD

**Issue by IL2** [rfrezino/RFindUnit#35]
Please update OmniThreadLibrary to fix wrong comparison in GUIDCompare:
[FixInsight Warning] GpListsFU.pas(2372): W512 Odd ELSE-IF condition (review lines 2372 and 2374):
```
function GUIDCompare(avalue1, avalue2: TGUID): integer;
...
  else if DWORD(guid1.D4[4]) < DWORD(guid2.D4[4]) then
    Result := -1
  else if DWORD(guid1.D4[4]) < DWORD(guid2.D4[4]) then //here should be >
    Result := 1
```
https://github.com/gabr42/OmniThreadLibrary/pull/65

**Comment by rfrezino** [comment]
I fixed punctually the problem. I'm thinking about to remove the OmniThread, and don't use it so much, maybe it's better to handle threads by myself.

**Comment by IL2** [comment]
Frankly, I wasn't be able to catch GUIDCompare function executing.
It seems that it is compiled, but never called while using RFindUnit.
