### ISSUE TITLE
ETransparentCanvasException on Ctrl-Shift-I

### ISSUE THREAD

**Issue by IL2** [rfrezino/RFindUnit#36]
Hit Ctrl-Shift-I and get exception:
\Thirdy\TransparentCanvas\TransparentCanvas.pas(538):   if not CanDrawGlowText then raise ETransparentCanvasException.Create('Cannot use DrawThemeTextEx');
```
procedure TCustomTransparentCanvas.InternalGlowTextOut(const ARect : TRect; const GlowSize: Integer; const Text: string;
  const Alignment : TAlignment; const Alpha: Byte; const ProcessBackColor : Boolean;
  const BackColor : TQuadColor);
...
  if not CanDrawGlowText then raise ETransparentCanvasException.Create('Cannot use DrawThemeTextEx');
```
Delphi 10 Update 1.

**Comment by rfrezino** [comment]
IL2, what is your Window's version ?

**Comment by IL2** [comment]
Windows 7 x86 SP1. No Aero, Classic desktop.
I'll try your fix and post soon.

**Comment by IL2** [comment]
Still not fixed. I'm tracing Ctrh-Shift-I reaction on TObject:
1) procedure TfrmMessage.ShowMessage; with Text='There is not possible uses to import.' parameter
2) it calls PrintOnCanvas;
3) which calls
`GlassCanvas.GlowTextOutBackColor(COORNER_MARGIN + MARGIN_PADING, MARGIN_PADING, 0, FTexto, clBlack, taLeftJustify, 10, 255);`
4) which calls
`InternalGlowTextOut(X, Y, GlowSize, Text, Alignment, Alpha, True, Background);`
5)
`InternalGlowTextOut(Rect(X, Y, X + TextSize.cx, Y + TextSize.cy), GlowSize, Text, Alignment, Alpha, ProcessBackColor, BackColor);`
6) which fails on
`if not CanDrawGlowText then raise ETransparentCanvasException.Create('Cannot use DrawThemeTextEx');`
because StyleServices.Enabled is False.
Exception is dropped silently, but nothing appears on the screen.

I believe the problem is in TransparentCanvas.pas which is third-party to the project.
