### ISSUE TITLE
RFindUnit changes global Windows timer resolution

### ISSUE THREAD

**Issue by IL2** [rfrezino/RFindUnit#38]
After install RFindUnit changes global Windows timer resolution from default 15ms to 1ms.
Due to this there is unneeded energy wasted
https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/
https://randomascii.wordpress.com/2016/03/08/power-wastage-on-an-idle-laptop/
especially on the laptop on battery.
That probably comes from OTL SetTimer call in

```
function TOTPWorker.Initialize: boolean;
...
  Task.SetTimer(1, 1000, @TOTPWorker.MaintainanceTimer);
```

Should I report to [OTL](https://github.com/gabr42/OmniThreadLibrary) instead?

**Comment by rfrezino** [comment]
Wow! Yes, I think it's better to report to Gabriel.

**Comment by IL2** [comment]
Done https://github.com/gabr42/OmniThreadLibrary/issues/68
I think this line actually causes the issue
`timeBeginPeriod(1);`
https://github.com/rfrezino/RFindUnit/search?utf8=%E2%9C%93&q=timeBeginPeriod

**Comment by rfrezino** [comment]
Im not using otl anymore
