### ISSUE TITLE
Not found const in Winapi.Windows.pas

### ISSUE THREAD

**Issue by jaclas** [rfrezino/RFindUnit#39]
Please see:

https://snap.ashampoo.com/uploads/2016-04-28/NdNkQzUM.png

**Comment by rfrezino** [comment]
I was without Delphi. Now it's ok again. I'll take a look at the problem.

**Comment by rfrezino** [comment]
I found the problem. It's a situation btw the Dcu32Int and DelphiAst. I don't know how to solve it yet.

**Comment by rfrezino** [comment]
jaclas, please send me your pas unit. rodrigofrezino@gmail.com

**Comment by rfrezino** [comment]
Jaclas, please run the "Process DCUs Files from Library Path"

**Comment by jaclas** [comment]
Nothing changed, still not found "vk_ret" :-(
