### ISSUE TITLE
RFindUnit is incompatible with Delphi Berlin

### ISSUE THREAD

**Issue by jaclas** [rfrezino/RFindUnit#40]
Incompatibility on helpers level and get access to private fields (SimpleParser.pas).

![rfunitbug](https://cloud.githubusercontent.com/assets/17312717/15659281/9abcb81e-26c8-11e6-983c-6141ea4f250a.png)

http://stackoverflow.com/questions/37351215/how-to-access-a-private-field-from-a-class-helper-in-delphi-10-1-berlin

**Comment by jkour** [comment]
This error is fixed in the updated version of DelphiAST

**Comment by rfrezino** [comment]
I merged Jkour branch!
Thank you,
