### ISSUE TITLE
Won't work in Delphinus

### ISSUE THREAD

**Issue by Memnarch** [rfrezino/RFindUnit#44]
Hi,
Just found a few issues which need to be adressed :)
- My Documentation states that you need to link a dproj/grouproj. A DPK does not work. 
- If you want to create an IDE-Expert, it must be a DLL anyway(please provide a meaningfull name)
- Search/Browsingpaths are copypaste errors, thoses paths do no exist on your structure
- for the first release (Package)Compiler_Min/Max should be identical.
- There seem to be more copy/paste errors like a logo.jpg which is not there.

Just noticed that the package is not yet listed by the Github-Api. A bit confused right now, maybe it needs some time.

PS: Starting with the Datadog api might have been easier, since this project needs a rewrite as IDE-Expert, to work with your thirdparty source.

**Comment by sglienke** [comment]
Seems like some issue with the readme file and the github api. For testing I created a fork and removed all text from the readme but "Delphinus-Support" and it lists the repository (given I also let it list forks with Delphinus does not do for a reason).

I think @Memnarch will open an issue at github.

**Comment by Memnarch** [comment]
Yup,
I'll contact github about it. @rfrezino in the meantime please fix the wrong project references by using a dproj.
