### ISSUE TITLE
Spring items not found

### ISSUE THREAD

**Issue by jaclas** [rfrezino/RFindUnit#46]
Please see:
![ashampoo_snap_2016 12 02_21h06m03s_002_](https://cloud.githubusercontent.com/assets/17312717/20848762/c9b9bb2e-b8d3-11e6-9c9b-657c3056f13d.png)

**Comment by jaclas** [comment]
Next example from spring:

![ashampoo_snap_2017 01 08_09h01m23s_001_](https://cloud.githubusercontent.com/assets/17312717/21748285/6099f0b2-d581-11e6-94e3-b212e349b9ec.png)

**Comment by rrezino** [comment]
Solved, it was a problem on DelphiAst, it was fixed
