### ISSUE TITLE
Expert does not compile

### ISSUE THREAD

**Issue by jaclas** [rfrezino/RFindUnit#48]
After last commits expert does not compile. Missing files:

RFindUnit.dpk
SimpleParser.inc (bad path)

And missing package for Berlin (include RFindUnitSplash.res)

**Comment by rrezino** [comment]
Jaclas I don't have access to Delphi Berlin, can you create a installation dir for it and send me a pull request ? 
Thank you!

**Comment by jaclas** [comment]
No, problem is with missing files (you remove it). Project has no dpk file (and resorce file from Splash too). 
SimpleParser.inc is in the subdirectory, so the compiler does not find the file (I change path in DelphiAST.Writer.pas:
{$I Thirdy\DelphiAST\SimpleParser\SimpleParser.inc}

**Comment by jaclas** [comment]
![vps_06](https://cloud.githubusercontent.com/assets/17312717/23852066/53083de0-07e6-11e7-9514-da24147eed1f.png)

**Comment by jaclas** [comment]
In Berlin still missing RFindUnitSplash.res (in Seattle directory exist), please add it.
Add please remove from RFindUnit.dpk linke with:

{$R *.otares}


> otares
> File with unknown resources generated during upgrade of pre XE2 project. (Unknown resources are resources that are not included in the build configuration, like version info, icon, manifest or styles.) 

[Emba documentation](http://docwiki.embarcadero.com/RADStudio/Berlin/en/File_Extensions_of_Files_Generated_by_RAD_Studio)

**Comment by jaclas** [comment]
Please remove include otares from Berlin dpk file:

```
package RFindUnit;

{$R *.res}
{$R *.otares}   <--- this

```


...and delete RFindUnit.otares file from Berlin folder.
Additionaly please add to Berlin folder missing file RFindUnitSplash.res

And please add clone of Berlin folder for Delphi Tokyo. I will check it.


thx for last interesting updates :-)

**Comment by rrezino** [comment]
fixed

**Comment by jaclas** [comment]
I successfully compiled RFindUnit in Tokyo, thx :-)
