### ISSUE TITLE
Ctrl + Shift + O is not working

### ISSUE THREAD

**Issue by KarlheinzJansen** [rfrezino/RFindUnit#51]
On my system Win10Pro (German), RADStudio Tokyo Pro (English) the keystroke Ctrl +Shift + O is not working.  Ctrl + Shift + A is working fine.

Installed AddOn => Gexpert

**Comment by rfrezino** [comment]
Is the short cut enabled on the config ? 
By nowbi can organize uses with ifdef or comments.

**Comment by KarlheinzJansen** [comment]
Yes, the short cut is enabled.

**Comment by rrezino** [comment]
Strangeee, same error here, I'm checking, but the IDE is blocking the shortcut to be called

**Comment by rrezino** [comment]
I needed to change it, in Tokyo for some reason it's not working.
you can download it now and use Ctrl + shift + u
