### ISSUE TITLE
Bad uses clause insert...

### ISSUE THREAD

**Issue by jaclas** [rfrezino/RFindUnit#58]
Example:

I have class TServerRoot in unit   ss.core.server.root.pas. I find it in RFindUnit, click Add and to uses secion is added:

uses
  ss.core.server.root.TServerRoot;

but should be only:

uses
 ss.core.server.root;

**Comment by rfrezino** [comment]
I made a mistake and sent changes to the master branch, I'm gonna close these last issues, because those bugs wont be in production, I'm preparing an interesting thing :D
