### ISSUE TITLE
Damaging class code by uses manager

### ISSUE THREAD

**Issue by jaclas** [rfrezino/RFindUnit#67]
I finally found simple example of bug in uses manager that has long irritated me:

![vps_2017 09 11_02](https://user-images.githubusercontent.com/17312717/30282942-07dd3210-9717-11e7-9056-046eaa63af9e.png)
![vps_2017 09 11_03](https://user-images.githubusercontent.com/17312717/30282944-0b3de620-9717-11e7-8192-26797b59a73c.png)
![vps_2017 09 11_04](https://user-images.githubusercontent.com/17312717/30282949-0d3f0ac6-9717-11e7-874d-8a9f375ba147.png)

and unit for reproduce problem:

[test.txt](https://github.com/rfrezino/RFindUnit/files/1293086/test.txt)

**Comment by jkour** [comment]
This bug annoys me so much. I uninstalled the package because of it.

Please please fix it.

**Comment by rrezino** [comment]
Fixed, temporary fix, but it's working at least.
